spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/JackedLab
    username: ajay
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect